name: dart_mastering
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  riverpod: ^1.0.3

dev_dependencies:
  lint: ^1.10.0
  meta: ^1.8.0
  test: ^1.16.0
