# @format

name: dart_mastering
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  path: ^1.8.0
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  lint: ^1.10.0
  meta: ^1.8.0
